# Name of website
title: Chaketeros Website

show_downloads: true

github:
  zip_url: https://github.com/AdriaSeSa/Chaketeros/releases/download/0.5/Chaketeros_Bomberman_v0.5.zip

# Your name to show in the footer
author: Adrià Sellarés

theme: jekyll-theme-midnight
