# Name of website
title: Chaketeros Website

show_downloads: true

github:
  zip_url: https://github.com/AdriaSeSa/Chaketeros/releases/download/1.0/Chaketeros_MegaBomberman_v1.0.zip
  tar_url: https://github.com/AdriaSeSa/Chaketeros/releases/download/1.0/Chaketeros_MegaBomberman_v1.0.zip

# Your name to show in the footer
author: Adrià Sellarés

theme: jekyll-theme-midnight
